version: '3'
services:
  PHP:
    container_name: PHP7.2-0.01
    image: ikasetebo/php7.2:v0.15
    networks:
      - app_bridge
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - D:/Repos/Docker-Images/PHP7/app/:/usr/share/nginx/html/
      - D:/Repos/Docker-Images/PHP7/nginx-conf/sites-enabled/default:/etc/nginx/sites-enabled/default
      - D:/Repos/Docker-Images/PHP7/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - D:/Repos/Docker-Images/PHP7/php-conf/php.ini:/etc/php/7.2/fpm/php.ini
      - D:/Repos/Docker-Images/PHP7/shared/:/shared/

networks:
  app_bridge:
    driver: bridge



